//! Adapter 2: `OAuthCallbackHandler` — T-006-PLATFORM-ADAPTERS.md L86-108. Trait
//! signature and error/result types are copied verbatim from the contract. No fields/variants
//! added or removed.

/// Platform-independent OAuth callback handler adapter trait (T-006 L86-108, T-202).
///
/// Implementations are injected at the composition root per T-006 Design Principles 1-2,
/// so core modules (OAuth state machine) depend only on this trait, not on any
/// platform/OS-specific implementations.
pub trait OAuthCallbackHandler: Send + Sync {
    /// Listen for an incoming OAuth callback on a temporary localhost HTTP listener.
    ///
    /// # Arguments
    ///
    /// * `expected_state` - The CSRF state token generated by `start()`. The callback
    ///   must include this exact value to prove it originated from this authorization flow.
    ///
    /// # Returns
    ///
    /// A `CallbackReceiver` wrapping a oneshot channel that will receive the callback
    /// result (code/error) when the user completes authorization in the browser.
    /// The receiver also includes the port number for building the `redirect_uri`.
    ///
    /// # Errors
    ///
    /// Returns `CallbackError::ListenerBindFailed` if the temporary HTTP listener
    /// on 127.0.0.1 cannot be started (rare, but may occur on systems with port
    /// binding issues).
    fn listen_for_callback(&self, expected_state: &str) -> Result<CallbackReceiver, CallbackError>;

    /// Open the system browser at the given OAuth authorization URL.
    ///
    /// # Arguments
    ///
    /// * `url` - The OAuth provider's authorization URL (must be `https://...`).
    ///   Examples: `https://api.oura.cloud/oauth/authorize?...`, etc.
    ///
    /// # Errors
    ///
    /// Returns `CallbackError::BrowserLaunchFailed` if:
    /// - The URL is not `https://` (security: reject `file://`, `javascript:`, etc.)
    /// - The system browser cannot be launched (OS error, no default browser)
    fn open_system_browser(&self, url: &str) -> Result<(), CallbackError>;
}

/// Receiver for OAuth callback results, wrapping tokio's oneshot channel.
///
/// The callback handler's `listen_for_callback()` returns this struct, which holds
/// the receiving end of a tokio oneshot channel. The application polls or awaits
/// this channel to receive the OAuth callback result (code or error) when the user
/// completes authorization in the browser.
#[derive(Debug)]
pub struct CallbackReceiver {
    /// Oneshot receiver that delivers the callback result or a callback-listener error.
    pub recv: tokio::sync::oneshot::Receiver<Result<CallbackResult, CallbackError>>,
    /// The port number on which the temporary HTTP listener is bound (127.0.0.1:{port}/callback).
    /// Used by the caller to construct the OAuth authorization URL's redirect_uri parameter.
    pub port: u16,
}

/// Represents the two possible OAuth callback outcomes: success or provider error.
#[derive(Debug, Clone)]
pub enum CallbackResult {
    /// Successful callback with authorization code and state token.
    ///
    /// # Fields
    ///
    /// * `code` - The authorization code from the provider (exchanged for access token in T-203)
    /// * `state` - The CSRF state token, must match `expected_state` passed to `listen_for_callback()`
    Success { code: String, state: String },

    /// Provider returned an error (user denied, invalid client, etc.)
    ///
    /// # Fields
    ///
    /// * `error` - OAuth error code (e.g., "access_denied", "invalid_client", "server_error")
    /// * `error_description` - Optional human-readable error message from the provider
    Error {
        error: String,
        error_description: Option<String>,
    },
}

/// Error type for OAuth callback handler operations.
#[derive(Debug, Clone)]
pub enum CallbackError {
    /// Temporary HTTP listener on 127.0.0.1 could not be started (T-301).
    ///
    /// Recovery: This is a temporary system issue; retry connecting the source.
    ListenerBindFailed,

    /// Callback was not received within the allowed time window (T-006 L104-106: 5 minutes).
    ///
    /// Recovery: User should cancel and retry the authorization flow.
    Timeout,

    /// System browser could not be launched (non-https URL, OS error, etc.)
    ///
    /// Recovery: User should verify browser is available and URL is valid.
    BrowserLaunchFailed,
}

impl std::fmt::Display for CallbackError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CallbackError::ListenerBindFailed => {
                write!(f, "OAuth callback listener could not be started")
            }
            CallbackError::Timeout => {
                write!(f, "OAuth callback timeout")
            }
            CallbackError::BrowserLaunchFailed => {
                write!(f, "failed to launch system browser")
            }
        }
    }
}

impl std::error::Error for CallbackError {}
